# Generated by Django 4.1 on 2023-12-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="email",
            field=models.EmailField(default="", max_length=254),
        ),
    ]
